version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: WARNING
    stream: ext://sys.stdout

loggers:
  # Root logger
  root:
    handlers: [console]
    level: WARNING
    propagate: yes

  # Your application logger
  lib:
    handlers: [console]
    level: WARNING
    propagate: no

# Example for uvicorn
uvicorn:
  handlers:
    default:
      class: logging.StreamHandler
      formatter: standard
      level: WARNING
      stream: ext://sys.stdout
  loggers:
    uvicorn:
      handlers: [default]
      level: WARNING
      propagate: no
